// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Representation of a Tax Class
 */
export type TaxClass = { id: bigint, 
/**
 * A legally defined item category specifying a tax percentage to apply to that item in a sale.
 */
class: string, 
/**
 * The amount, in percentage, of tax to apply.
 */
amount: bigint, };
