/// Defines CRUD Tauri commands for given database tables. This macro creates
/// a struct that represents the data in the SQLite database, with the field
/// names matching the ones found in the database. The `id` field is
/// automatically generated by this macro and does not need to be added to the
/// input struct (it has type [`i64`]).
///
/// ## Created functions
///
/// This macro creates four functions based on the struct name when a struct
/// is created given in the macro input. For example using the struct name
/// `Appointment` will result in the following functions being created:
///
/// ```rs
/// pub(crate) fn create_appointment(appointment: Appointment) -> Result<(), String> {}
/// pub(crate) fn read_appointment() -> Result<Vec<Appointment>, String> {}
/// pub(crate) fn update_appointment(with: Appointment) -> Result<(), String> {}
/// pub(crate) fn delete_appointment(id: i64) -> Result<(), String> {}
/// ```
///
/// ## Use
///
/// This macro is used to reduce the boilerplate code for setting up CRUD
/// operations as well as to allow to easily define operations for newer tables
/// easier.
///
#[macro_export]
macro_rules! define_table_crud {
  (
    $(
      $(#[$attr: meta])*
      $v_outer: vis struct $table_name: ident {
        $(
          $(#[$k_comment: meta])*
          $k: ident: $t: ty
        ),+$(,)?
      }
    )+
  ) => {
    use ::rusqlite::{Connection, Error};
    use ::serde::{Serialize, Deserialize};
    use ::pastey::paste;
    use ::ts_rs::TS;

    $(
      $(#[$attr])*
      #[derive(Debug, Default, Serialize, Deserialize, TS)]
      #[serde(rename_all = "camelCase")]
      #[ts(export)]
      $v_outer struct $table_name {
        id: i64,
        $(
          $(#[$k_comment])*
          pub $k: $t,
        )+
      }

      paste! {
        #[tauri::command]
        pub(crate) fn [<create_ $table_name:snake>]([<$table_name:lower>]: $table_name) -> Result<(), String> {
          err_wrap(|| {
            let connection: Connection = Connection::open("soteria-db")?;
            let table_name: &str = stringify!([<$table_name: snake>]);
            let $table_name { id: _, $($k,)+ } = [<$table_name:lower>];

            let mut fields_param = Vec::new();

            for i in 0..(stringify!($($k)+).split(" ").count()) {
              fields_param.push(format!("?{}", i + 1));
            }
            let fields = stringify!($($k)+).split(" ").collect::<Vec<&str>>();

            let command = format!(
              "INSERT INTO {} ({}) VALUES ({})",
              table_name,
              fields.join(","),
              fields_param.join(",")
            );

            connection.execute(&command, ($($k),+));
            connection.close().map_err(|(_, v)| v)?;
            Ok(())
        })
      }

        #[tauri::command]
        pub(crate) fn [<read_ $table_name:snake>]() -> Result<Vec<$table_name>, String> {
          err_wrap(|| {
            let connection: Connection = Connection::open("soteria-db")?;
            let table_name: &str = stringify!([<$table_name: snake>]);
            let mut conn_stmt = connection.prepare(&format!("SELECT * FROM {}", table_name))?;

            let collect_values: Result<Vec<$table_name>, Error> = conn_stmt.query_map([], |v| {
              let (id, $($k,)+) = v.try_into()?;
              Ok($table_name { id, $($k,)+ })
            })?.collect();

            let values = collect_values?;
            drop(conn_stmt);

            connection.close().map_err(|(_, v)| v)?;
            Ok(values)
          })
        }

        #[tauri::command]
        pub(crate) fn [<read_one_ $table_name: snake>](id: i64) -> Result<Option<$table_name>, String> {
          err_wrap(|| {
            let connection: Connection = Connection::open("soteria-db")?;
            let table_name: &str = stringify!([<$table_name: snake>]);

            let result = connection.query_one(&format!("SELECT * FROM {} WHERE id = ?1;", table_name), (id,), |v| {
              let (id, $($k,)+) = v.try_into()?;
              Ok($table_name { id, $($k,)+ })
            })?;
            connection.close().map_err(|(_, v)| v)?;
             Ok(Some(result))
          })
        }

        #[tauri::command]
        pub(crate) fn [<update_ $table_name: snake>](with: $table_name) -> Result<(), String> {
          err_wrap(|| {
            let connection: Connection = Connection::open("soteria-db")?;
            let table_name: &str = stringify!([<$table_name: snake>]);
            let $table_name { id: _, $($k,)+ } = with;

            let mut i = 1;
            let mut fields = Vec::new();
            $(
              fields.push(format!("{} = ?{}", stringify!($k), i));
              i += 1;
            )+
            let command = format!("UPDATE {} SET {} WHERE id = {}", table_name, fields.join(", "), with.id);

            connection.execute(&command, ($($k,)+))?;
            connection.close().map_err(|(_, v)| v)?;
            Ok(())
          })
        }

        #[tauri::command]
        pub(crate) fn [<delete_ $table_name: snake>](id: i64) -> Result<(), String> {
          err_wrap(|| {
            let connection: Connection = Connection::open("soteria-db")?;
            let table_name: &str = stringify!([<$table_name: snake>]);

            connection.execute(&format!("DELETE FROM {} WHERE id = ?1;", table_name), (id,))?;
            connection.close().map_err(|(_, v)| v)?;
            Ok(())
          })
        }
      }
    )+

    fn err_wrap<T, F>(cb: F) -> Result<T, String>
    where
      F: FnOnce() -> Result<T, Error>,
    {
      cb().map_err(|e| e.to_string())
    }
  }
}
