#!/usr/bin/env powershell
$ErrorActionPreference = 'Stop'
$PSNativeCommandErrorActionPreference = $true

Set-Item -Path "Env:ARG0" -Value "$PSCommandPath"
for ($i = 0; $i -lt $args.Count; $i++) {
  Set-Item -Path "Env:ARG$($i + 1)" -Value "$($args[$i])"
}

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

deno run --allow-read --allow-sys --allow-run --allow-env npm:@commitlint/cli --edit $env:ARG1

if ($LASTEXITCODE -ne 0) {
  exit $LASTEXITCODE
}


