on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: "Install moon"
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
          cache: true

      - name: "Add cargo to path"
        run: 'echo "$HOME/.cargo/bin" >> $GITHUB_PATH'

      - name: "Install Rust Dependencies"
        run: |
          sudo apt update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: "Install Rust Toolchain"
        run: |
          rm -rf ~/.rustup/toolchains/*
          ~/.cargo/bin/cargo --version

      - name: "Setup Moon Toolchains"
        run: "moon setup"

      - name: "Run tests for Rust code"
        run: "moon run :lint"
